# Generated by Django 3.1.5 on 2021-01-21 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=90)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=180)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
                ('geo_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travel_agency_app.geolocation')),
            ],
        ),
    ]
