# Generated by Django 3.1.5 on 2021-01-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0005_locationmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationManager',
        ),
    ]
