# Generated by Django 3.1.5 on 2021-01-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0006_delete_locationmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
