# Generated by Django 3.1.5 on 2021-01-23 21:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0009_auto_20210123_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenWeatherTempRanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('weather_range', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2)),
            ],
        ),
    ]
