# Generated by Django 3.1.5 on 2021-01-23 21:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0010_openweathertempranges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openweathertempranges',
            name='weather_range',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
