# Generated by Django 3.1.5 on 2021-01-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0011_auto_20210123_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_a_capital',
            field=models.BooleanField(default=False),
        ),
    ]
