# Generated by Django 3.1.5 on 2021-01-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0013_auto_20210123_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_capital',
            field=models.BooleanField(),
        ),
    ]
