# Generated by Django 3.1.5 on 2021-01-24 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0015_auto_20210124_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='destination',
        ),
        migrations.AddField(
            model_name='destination',
            name='destination',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_agency_app.location'),
        ),
    ]
