# Generated by Django 3.1.5 on 2021-01-25 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0018_auto_20210125_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourpackage',
            old_name='tour_package',
            new_name='destination',
        ),
    ]
