# Generated by Django 3.1.5 on 2021-01-25 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0019_auto_20210125_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dangerlevel',
            old_name='destination',
            new_name='destinations',
        ),
        migrations.RenameField(
            model_name='destinationtype',
            old_name='destination',
            new_name='destinations',
        ),
    ]
