# Generated by Django 3.1.5 on 2021-01-25 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0020_auto_20210125_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_agency_app.destination'),
        ),
    ]
