# Generated by Django 3.1.5 on 2021-01-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0021_auto_20210125_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationtype',
            name='destinations',
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_types',
            field=models.ManyToManyField(blank=True, to='travel_agency_app.DestinationType'),
        ),
    ]
