# Generated by Django 3.1.5 on 2021-01-25 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0022_auto_20210125_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='destination_types',
        ),
        migrations.AddField(
            model_name='destinationtype',
            name='danger_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_agency_app.destination'),
        ),
        migrations.RemoveField(
            model_name='dangerlevel',
            name='destinations',
        ),
        migrations.AddField(
            model_name='dangerlevel',
            name='destinations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_agency_app.destination'),
        ),
    ]
