# Generated by Django 3.1.5 on 2021-01-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0025_auto_20210125_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourpackage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='dangerlevel',
            old_name='destinations',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='destinationtype',
            old_name='destinations',
            new_name='destination',
        ),
    ]
