# Generated by Django 3.1.5 on 2021-01-25 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0026_auto_20210125_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Availability',
            name='tour_package',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='travel_agency_app.tourpackage'),
        ),
        migrations.AlterField(
            model_name='dangerlevel',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='danger_level', to='travel_agency_app.destination'),
        ),
        migrations.AlterField(
            model_name='destinationtype',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='destination_type', to='travel_agency_app.destination'),
        ),
    ]
