# Generated by Django 3.1.5 on 2021-01-25 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0027_auto_20210125_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Availability',
            name='tour_package',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Availability', serialize=False, to='travel_agency_app.tourpackage'),
        ),
    ]
