# Generated by Django 3.1.5 on 2021-01-25 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0029_auto_20210125_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCapacity',
            fields=[
                ('capacity', models.IntegerField()),
                ('tour_package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='travel_agency_app.tourpackage')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
