# Generated by Django 3.1.5 on 2021-01-25 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0030_tourpackagecapacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('tour_package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travel_agency_app.tourpackage')),
            ],
        ),
    ]
