# Generated by Django 3.1.5 on 2021-01-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0032_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='tour_package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='travel_agency_app.tourpackage'),
        ),
    ]
