# Generated by Django 3.1.5 on 2021-01-25 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0033_auto_20210125_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcapacity',
            name='tour_package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity', to='travel_agency_app.tourpackage'),
        ),
    ]
