# Generated by Django 3.1.5 on 2021-01-25 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0039_auto_20210125_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='destination',
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='travel_agency_app.location'),
        ),
    ]
