# Generated by Django 3.1.5 on 2021-01-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0041_auto_20210125_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='destination',
        ),
        migrations.AddField(
            model_name='destination',
            name='tours_packages',
            field=models.ManyToManyField(related_name='destination', to='travel_agency_app.TourPackage'),
        ),
    ]
