# Generated by Django 3.1.5 on 2021-01-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0043_auto_20210126_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourpackage',
            old_name='destination',
            new_name='destination_name',
        ),
    ]
