# Generated by Django 3.1.5 on 2021-01-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0045_auto_20210126_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dangerlevel',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='destinationtype',
            name='destination',
        ),
        migrations.AddField(
            model_name='destination',
            name='danger_level',
            field=models.ManyToManyField(to='travel_agency_app.DangerLevel'),
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_type',
            field=models.ManyToManyField(to='travel_agency_app.DestinationType'),
        ),
    ]
