# Generated by Django 3.1.5 on 2021-01-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0046_auto_20210126_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='destination',
        ),
        migrations.AddField(
            model_name='destination',
            name='destination',
            field=models.ManyToManyField(blank=True, related_name='tours', to='travel_agency_app.TourPackage'),
        ),
    ]
