# Generated by Django 3.1.5 on 2021-01-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0047_auto_20210126_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='destination',
        ),
        migrations.AddField(
            model_name='destination',
            name='tour_package',
            field=models.ManyToManyField(blank=True, related_name='destination', to='travel_agency_app.TourPackage'),
        ),
    ]
