# Generated by Django 3.1.5 on 2021-01-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0048_auto_20210126_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='registries',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='tour_package',
            field=models.ManyToManyField(related_name='destination', to='travel_agency_app.TourPackage'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
