# Generated by Django 3.1.5 on 2021-01-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0050_remove_availability_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='availability',
            field=models.JSONField(null=True),
        ),
    ]
