# Generated by Django 3.1.5 on 2021-01-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0051_availability_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='availability',
        ),
    ]
