# Generated by Django 3.1.5 on 2021-01-27 16:41

from django.db import migrations, models
import travel_agency_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0052_remove_availability_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='availability',
            field=models.DateField(null=True, validators=[travel_agency_app.models.validate_format]),
        ),
        migrations.RemoveField(
            model_name='availability',
            name='tour_package',
        ),
        migrations.AddField(
            model_name='availability',
            name='tour_package',
            field=models.ManyToManyField(blank=True, related_name='available_dates', to='travel_agency_app.TourPackage'),
        ),
    ]
