# Generated by Django 3.1.5 on 2021-01-27 16:49

from django.db import migrations, models
import travel_agency_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0053_auto_20210127_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='availability',
            field=models.DateField(default='2021-08-15', validators=[travel_agency_app.models.validate_format]),
            preserve_default=False,
        ),
    ]
