# Generated by Django 3.1.5 on 2021-01-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0056_auto_20210127_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='tour_package',
            field=models.ManyToManyField(to='travel_agency_app.TourPackage'),
        ),
    ]
